### ISSUE TITLE
Unhandled exception error when XML file contains extraneous &gt;

### ISSUE THREAD

**Issue by dthaler** [dthaler/ArtemisMissionEditor#3]
https://artemis.forumchitchat.com/post/show_single_post?pid=1321705806&postcount=131&forum=309882

Using https://d28lcup14p4e72.cloudfront.net/145634/5619819/MISS_Dawn_Patrol_2.0.zip
Unzip and use the mission editor to try to open MISS_Dawn_Partrol_2.0.xml

This hits the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArtemisMissionEditor.MissionNode_Event.FromXml(XmlNode item)
   at ArtemisMissionEditor.MissionNode.NewFromXML(XmlNode item)
   at ArtemisMissionEditor.Mission.FromXml(String text, Boolean suppressLoadingSignal, Boolean fromState)
   at ArtemisMissionEditor.Mission.FromFile(String fileName)
   at ArtemisMissionEditor.Mission.Open(Boolean force)
   at ArtemisMissionEditor.Forms.FormMain._E_FM_ms_Main_File_OpenMission_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ArtemisMissionEditor
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Artemis%20Mission%20Editor/ArtemisMissionEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Drawing.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

https://artemis.forumchitchat.com/post/show_single_post?pid=1330894029&postcount=134&forum=309882

```
There's an extraneous HTML bracket tag tacked onto a closing bracket:

<event name="Terran Task Force" id_arme="5dfa3020-62a3-4dfa-aad8-e587c69f4c13">
<if_variable name="TETF" comparator="EQUALS" value="1.0"/>
<if_variable name="Terran_Bounty" comparator="GREATER_EQUAL" value="5.0"/>
<create type="enemy" x="77900.0" y="0.0" z="8004.0" name="TSN Eliminator" raceKeys="TSN" hullKeys="Battleship" sideValue="1"/>
<create type="enemy" x="77900.0" y="0.0" z="9005.0" name="TSN Cleaner" raceKeys="TSN" hullKeys="Juggernaut" sideValue="1"/>
<set_variable name="TETF" value="0.0"/>
<set_comms_button text="Dragon Tooth Refuge Bounty" sideValue="2"/>&gt;
<set_variable name="Bounty_Message" value="1.0"/>
<incoming_comms_text from="Radiance Terminal">To all vessels, Pirating will no longer be tolerated. A bounty has been post for all pirating ships Dead or Alive. Justice will be delivered and order will be restored in this sector. </incoming_comms_text>
<log text="Bounty: Wanted by the Terrans"/>
</event>


Delete the "&gt;" and it should load into the mission editor correctly.
```

**Comment by dthaler** [comment]
Fixed in v2.8.1
